### ISSUE TITLE
Add flags to CI to allow skipping failed lint and tests

### ISSUE THREAD

**Issue by AlexSkrypnyk** [AlexSkrypnyk/scaffold#116]
```yaml
  - name: Check coding standards
    run: composer lint || [ "${CI_LINT_IGNORE_FAILURE:-0}" -eq 1 ]

  - name: Run tests
    run: XDEBUG_MODE=coverage composer test || [ "${CI_TEST_IGNORE_FAILURE:-0}" -eq 1 ]
```
